## Data Cleaning Tool

### Import Library

In [106]:
import importlib
import Data_Source 
importlib.reload(Data_Source)
from Data_Source import *

### Data Load

In [2]:
df = Data_Load("Massi_Data/Data_Cleaning_Practice_Dataset.xlsx")
df.head(3)

,Customer_ID,First_Name,Last_Name,Gender,Age,Email,Phone,City,State,Product,Category,Quantity,Unit_Price,Total_Sales,Order_Date,Payment_Method,Customer_Rating
0,C0001,Karan,Soni,Male,47,customer1@gmail.com,9.823315e+09,Surat,Gujarat,Desk,Furniture,4.0,9000.0,36000,2026-04-13 00:00:00,Credit Card,3.0
1,C0002,Rahul,Joshi,Female,29,customer2@gmail.com,9.898410e+09,Bhavnagar,Gujarat,Desk,Furniture,3.0,9000.0,27000,2026-02-22 00:00:00,Credit Card,4.0
2,C0003,Nisha,Dave,Male,39,customer3@gmail.com,9.840350e+09,Vadodara,Gujarat,Chair,Furniture,2.0,7000.0,14000,2026-03-30 00:00:00,UPI,3.0

### Show Total Row And Cloumn

In [57]:
da = Dataset_Short_Summery(df)
da

Data Set Shape (292, 17)
Data Set All Cloumn Index(['Customer_ID', 'First_Name', 'Last_Name', 'Gender', 'Age', 'Email',
       'Phone', 'City', 'State', 'Product', 'Category', 'Quantity',
       'Unit_Price', 'Total_Sales', 'Order_Date', 'Payment_Method',
       'Customer_Rating'],
      dtype='str')
Total Rows 292
Total Cloumn 17

### DataSet Information

In [90]:
info = Show_Data_Info(df)
info

<class 'pandas.DataFrame'>
Index: 292 entries, 0 to 294
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      292 non-null    str
 1   First_Name       292 non-null    str
 2   Last_Name        292 non-null    str
 3   Gender           292 non-null    str
 4   Age              292 non-null    float64
 5   Email            292 non-null    str
 6   Phone            292 non-null    float64
 7   City             292 non-null    str
 8   State            292 non-null    str
 9   Product          292 non-null    str
 10  Category         292 non-null    category
 11  Quantity         292 non-null    float64
 12  Unit_Price       292 non-null    float64
 13  Order_Date       292 non-null    datetime64[us]
 14  Customer_Rating  292 non-null    float64
dtypes: category(1), datetime64[us](1), float64(5), str(8)
memory usage: 34.5 KB

### Summery Dataset

In [91]:
des = Summery_Data(df)
des

,Age,Phone,Quantity,Unit_Price,Order_Date,Customer_Rating
count,292.000000,2.920000e+02,292.000000,292.000000,292,292.000000
mean,38.224258,9.822127e+09,3.020594,13093.427865,2026-03-30 09:12:19.726027,2.948470
min,19.000000,1.234500e+04,-2.000000,800.000000,2026-01-01 00:00:00,0.000000
25%,30.000000,9.831825e+09,2.000000,2500.000000,2026-02-15 18:00:00,2.000000
50%,38.620805,9.855315e+09,3.000000,7000.000000,2026-03-27 00:00:00,3.000000
75%,46.000000,9.881211e+09,4.000000,12000.000000,2026-05-20 06:00:00,4.000000
max,150.000000,9.899817e+09,5.000000,55000.000000,2026-06-29 00:00:00,6.000000
std,11.982867,5.774007e+08,1.377128,16385.334316,NaN,1.426585

### Show Data Type

In [81]:
DataType = Show_Data_Type(df)
DataType

Customer_ID                   str
First_Name                    str
Last_Name                     str
Gender                        str
Age                       float64
Email                         str
Phone                     float64
City                          str
State                         str
Product                       str
Category                 category
Quantity                  float64
Unit_Price                float64
Order_Date         datetime64[us]
Customer_Rating           float64
dtype: object

### Number Convert
###### Give Two Parameter 1) DataObject , 2) column_name

In [103]:
Number = Change_Data_Type_into_Number(df,"Age")

### Date Convert

In [104]:
Dates = Change_Data_Type_into_Date(df,"Order_Date")

### Category Convert

In [105]:
Cat = Change_Data_Type_into_Category(df,"Category")

### Missing Value Show

In [82]:
M = Missing_Value_Show(df)
M

Customer_ID        0
First_Name         0
Last_Name          0
Gender             0
Age                0
Email              0
Phone              0
City               0
State              0
Product            0
Category           0
Quantity           0
Unit_Price         0
Order_Date         0
Customer_Rating    0
dtype: int64

### Numberic Missing Value Handel

In [16]:
num = Numberic_Value_Handel(df,"Unit_Price")

### Category Missing Value Handel

In [20]:
cate = Category_Value_Handel(df,"City")

### Remove Missing Value

In [22]:
rev = Remove_Missing_Value(df)
rev

### Show Duplicated Value

In [88]:
dup = Show_Duplicated_Value(df)
dup

np.int64(0)

### Any Cloumn In Duplicated

In [89]:
col = Show_Duplicated_Coumn(df,"Customer_ID")
col

np.int64(0)

### Remove Duplicates Value

In [40]:
removedup = Remove_Dupicated_Value(df)
removedup

### Drop Any Cloumn
###### give two argument 1 is dataset object sencond list of value

In [64]:
l1 = ["Total_Sales","Payment_Method"]
dro = Drop_Any_Column(df,l1)

### Show Data Quality

In [80]:
qu = Data_In_Value(df)

Customer_ID
C0001    1
C0002    1
C0003    1
C0004    1
C0005    1
        ..
C0290    1
C0292    1
C0293    1
C0294    1
C0295    1
Name: count, Length: 292, dtype: int64
First_Name
Aditya    17
Priya     17
Pooja     14
Neha      13
Sneha     13
Anjali    13
Yash      12
Khushi    12
Karan     11
Rahul     11
Riya      11
Ravi      11
Parth     11
Hetal      9
Isha       9
Nikhil     9
Raj        9
Komal      8
Dev        8
Manav      8
Arjun      8
Mansi      8
Jay        7
Harsh      7
Het        7
Nisha      6
Meera      6
Amit       6
Tanvi      6
Diya       5
Name: count, dtype: int64
Last_Name
Dave     60
Shah     53
Soni     51
Patel    49
Mehta    43
Joshi    36
Name: count, dtype: int64
Gender
Female    151
Male      139
F           1
M           1
Name: count, dtype: int64
Age
46.000000     13
29.000000     12
39.000000     12
35.000000     12
50.000000     12
53.000000     11
31.000000     11
30.000000     11
41.000000     11
54.000000     10
20.000000     10
38.000000     10
40.000000     10
52.000000     10
42.000000      9
43.000000      9
51.000000      9
26.000000      9
34.000000      9
44.000000      8
37.000000      7
32.000000      7
47.000000      6
22.000000      6
45.000000      6
21.000000      6
25.000000      5
23.000000      5
24.000000      5
33.000000      5
49.000000      5
48.000000      4
27.000000      4
28.000000      4
19.000000      3
36.000000      3
38.241611      2
150.000000     1
Name: count, dtype: int64
Email
customer1@gmail.com      1
customer2@gmail.com      1
customer3@gmail.com      1
customer4@gmail.com      1
customer5@gmail.com      1
                        ..
customer290@gmail.com    1
customer292@gmail.com    1
customer293@gmail.com    1
customer294@gmail.com    1
customer295@gmail.com    1
Name: count, Length: 292, dtype: int64
Phone
9.823315e+09    1
9.898410e+09    1
9.840350e+09    1
9.875285e+09    1
9.854739e+09    1
               ..
9.884314e+09    1
9.815994e+09    1
9.863789e+09    1
9.842437e+09    1
9.864441e+09    1
Name: count, Length: 292, dtype: int64
City
Surat        68
Bhavnagar    60
Ahmedabad    58
Rajkot       53
Vadodara     50
 rajkot       1
SURAT         1
Ahmedbad      1
Name: count, dtype: int64
State
Gujarat    292
Name: count, dtype: int64
Product
Chair         51
Monitor       43
Mouse         37
Keyboard      35
Laptop        34
Desk          32
Headphones    32
Tablet        27
laptop         1
Name: count, dtype: int64
Category
Electronics    208
Furniture       82
ELECTRONICS      1
electronics      1
Name: count, dtype: int64
Quantity
 4.000000    73
 2.000000    70
 3.000000    51
 5.000000    50
 1.000000    46
-2.000000     1
 3.013378     1
Name: count, dtype: int64
Unit_Price
7000.000000     50
12000.000000    43
800.000000      36
1500.000000     35
55000.000000    34
9000.000000     33
2500.000000     32
22000.000000    28
12980.936455     1
Name: count, dtype: int64
Order_Date
2026-01-01    5
2026-03-03    5
2026-04-23    5
2026-02-23    5
2026-01-25    5
             ..
2026-05-17    1
2026-05-11    1
2026-04-04    1
2026-06-17    1
2026-04-15    1
Name: count, Length: 142, dtype: int64
Customer_Rating
1.000000    64
3.000000    62
4.000000    60
5.000000    52
2.000000    51
2.953177     1
6.000000     1
0.000000     1
Name: count, dtype: int64

### Clean Data Value

In [85]:
cl = Category_Object_Value(df)

0      C0001
1      C0002
2      C0003
3      C0004
4      C0005
       ...
289    C0290
291    C0292
292    C0293
293    C0294
294    C0295
Name: Customer_ID, Length: 292, dtype: str
0       Karan
1       Rahul
2       Nisha
3       Pooja
4       Komal
        ...
289    Anjali
291    Anjali
292     Sneha
293      Yash
294       Raj
Name: First_Name, Length: 292, dtype: str
0       Soni
1      Joshi
2       Dave
3      Mehta
4      Patel
       ...
289     Soni
291     Soni
292    Mehta
293     Dave
294    Joshi
Name: Last_Name, Length: 292, dtype: str
0        Male
1      Female
2        Male
3      Female
4        Male
        ...
289    Female
291      Male
292      Male
293    Female
294    Female
Name: Gender, Length: 292, dtype: str
0        Customer1@Gmail.Com
1        Customer2@Gmail.Com
2        Customer3@Gmail.Com
3        Customer4@Gmail.Com
4        Customer5@Gmail.Com
               ...
289    Customer290@Gmail.Com
291    Customer292@Gmail.Com
292    Customer293@Gmail.Com
293    Customer294@Gmail.Com
294    Customer295@Gmail.Com
Name: Email, Length: 292, dtype: str
0          Surat
1      Bhavnagar
2       Vadodara
3          Surat
4       Vadodara
         ...
289    Ahmedabad
291    Bhavnagar
292     Vadodara
293    Bhavnagar
294     Vadodara
Name: City, Length: 292, dtype: str
0      Gujarat
1      Gujarat
2      Gujarat
3      Gujarat
4      Gujarat
        ...
289    Gujarat
291    Gujarat
292    Gujarat
293    Gujarat
294    Gujarat
Name: State, Length: 292, dtype: str
0          Desk
1          Desk
2         Chair
3      Keyboard
4          Desk
         ...
289    Keyboard
291    Keyboard
292       Mouse
293     Monitor
294        Desk
Name: Product, Length: 292, dtype: str

0      47.0
1      29.0
2      39.0
3      46.0
4      22.0
       ...
289    46.0
291    51.0
292    26.0
293    40.0
294    46.0
Name: Age, Length: 292, dtype: float64
0      9.823315e+09
1      9.898410e+09
2      9.840350e+09
3      9.875285e+09
4      9.854739e+09
           ...
289    9.884314e+09
291    9.815994e+09
292    9.863789e+09
293    9.842437e+09
294    9.864441e+09
Name: Phone, Length: 292, dtype: float64
0      4.0
1      3.0
2      2.0
3      2.0
4      2.0
      ...
289    4.0
291    4.0
292    1.0
293    5.0
294    4.0
Name: Quantity, Length: 292, dtype: float64
0       9000.0
1       9000.0
2       7000.0
3       1500.0
4       9000.0
        ...
289     1500.0
291     1500.0
292      800.0
293    12000.0
294     9000.0
Name: Unit_Price, Length: 292, dtype: float64
0      3.0
1      4.0
2      3.0
3      1.0
4      5.0
      ...
289    1.0
291    1.0
292    2.0
293    4.0
294    1.0
Name: Customer_Rating, Length: 292, dtype: float64

### Data Summery Report

In [107]:
rs = Data_Quality_Report(df)
rs

,Column,Unique Value,Missing Value,Duplicate,Data Type
Customer_ID,Customer_ID,292,0,0,str
First_Name,First_Name,30,0,262,str
Last_Name,Last_Name,6,0,286,str
Gender,Gender,4,0,288,str
Age,Age,38,0,254,float64
Email,Email,292,0,0,str
Phone,Phone,292,0,0,float64
City,City,8,0,284,str
State,State,1,0,291,str
Product,Product,9,0,283,str
Category,Category,4,0,288,category
Quantity,Quantity,7,0,285,float64
Unit_Price,Unit_Price,9,0,283,float64
Order_Date,Order_Date,142,0,150,datetime64[us]
Customer_Rating,Customer_Rating,8,0,284,float64

### Clean Data Save

In [102]:
Data_save("D:/All_Project_Data/PYTHON_PROJECTS/Data Cleaning Tool/Clean_Data",df,".json")